USE warehouse;
SET sql_log_bin = OFF;
CREATE USER IF NOT EXISTS 'rupert'@'%' IDENTIFIED WITH caching_sha2_password BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'rupert'@'%';
FLUSH PRIVILEGES;

# Variable Sanity Check
SHOW VARIABLES LIKE 'gtid_mode';
SHOW VARIABLES LIKE 'log_bin';
SHOW VARIABLES LIKE 'sql_log_bin';
SHOW VARIABLES LIKE 'binlog_format';

# Debugging
SHOW MASTER STATUS;
SHOW BINARY LOGS;
SHOW BINLOG EVENTS IN 'mysql-bin.000001' LIMIT 11000;

ALTER TABLE DimTitle AUTO_INCREMENT = 11923617;
SET GLOBAL auto_increment_offset = 1;
SET GLOBAL auto_increment_increment = 3;

CHANGE REPLICATION SOURCE TO SOURCE_HOST="stadvdb2.rinaldolee.com", SOURCE_USER="rupert", 
SOURCE_PASSWORD="password", SOURCE_PORT=3306, SOURCE_AUTO_POSITION=1, GET_SOURCE_PUBLIC_KEY=1 FOR CHANNEL "Node2ToNode1";
CHANGE REPLICATION SOURCE TO SOURCE_HOST="stadvdb3.rinaldolee.com", SOURCE_USER="rupert", 
SOURCE_PASSWORD="password", SOURCE_PORT=3306, SOURCE_AUTO_POSITION=1, GET_SOURCE_PUBLIC_KEY=1 FOR CHANNEL "Node3ToNode1";

CHANGE REPLICATION FILTER 
    REPLICATE_DO_TABLE = (warehouse.DimTitle)
FOR CHANNEL 'Node2ToNode1';

CHANGE REPLICATION FILTER 
    REPLICATE_DO_TABLE = (warehouse.DimTitle)
FOR CHANNEL 'Node3ToNode1';

START REPLICA FOR CHANNEL "Node2ToNode1";
START REPLICA FOR CHANNEL "Node3ToNode1";

SHOW REPLICA STATUS FOR CHANNEL 'Node2ToNode1';
SHOW REPLICA STATUS FOR CHANNEL 'Node3ToNode1';

SET sql_log_bin = ON;