USE nodedb;
SET sql_log_bin = OFF;
CREATE USER IF NOT EXISTS 'rupert'@'%' IDENTIFIED WITH caching_sha2_password BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'rupert'@'%';
FLUSH PRIVILEGES;

# Variable Sanity Check
SHOW VARIABLES LIKE 'gtid_mode';
SHOW VARIABLES LIKE 'log_bin';
SHOW VARIABLES LIKE 'sql_log_bin';
SHOW VARIABLES LIKE 'binlog_format';
SHOW VARIABLES LIKE 'enforce_gtid_consistency';

ALTER TABLE DimTitle AUTO_INCREMENT = 11923617;
SET GLOBAL auto_increment_offset = 1;
SET GLOBAL auto_increment_increment = 3;

DELIMITER @@
CREATE TRIGGER update_version
BEFORE UPDATE ON DimTitle
FOR EACH ROW
BEGIN
    SET NEW.version = OLD.version + 1;
END;@@
DELIMITER ;

STOP REPLICA FOR CHANNEL "Node2ToNode1";
STOP REPLICA FOR CHANNEL "Node3ToNode1";

CHANGE REPLICATION SOURCE TO SOURCE_HOST="stadvdb2.rinaldolee.com", SOURCE_USER="rupert", 
SOURCE_PASSWORD="password", SOURCE_PORT=3306, SOURCE_AUTO_POSITION=1, GET_SOURCE_PUBLIC_KEY=1 FOR CHANNEL "Node2ToNode1";
CHANGE REPLICATION SOURCE TO SOURCE_HOST="stadvdb3.rinaldolee.com", SOURCE_USER="rupert", 
SOURCE_PASSWORD="password", SOURCE_PORT=3306, SOURCE_AUTO_POSITION=1, GET_SOURCE_PUBLIC_KEY=1 FOR CHANNEL "Node3ToNode1";

CHANGE REPLICATION FILTER 
    REPLICATE_DO_TABLE = (nodedb.DimTitle)
FOR CHANNEL 'Node2ToNode1';

CHANGE REPLICATION FILTER 
    REPLICATE_DO_TABLE = (nodedb.DimTitle)
FOR CHANNEL 'Node3ToNode1';

START REPLICA FOR CHANNEL "Node2ToNode1";
START REPLICA FOR CHANNEL "Node3ToNode1";

SHOW REPLICA STATUS;

SET sql_log_bin = ON;

